# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directories:
      - "/dimp-auth"
      - "/clyde-bot"
      - "/clyde-dashboard"
      - "/clyde-server"
    schedule:
      interval: "weekly"
